services:
  - type: web
    name: snappl-pokemon-market
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install numpy pandas plotly streamlit streamlit-authenticator requests python-dateutil pyyaml opencv-python pytesseract
      pip install --no-deps .
    startCommand: streamlit run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
      - key: STREAMLIT_SERVER_PORT
        value: 5000
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
    domains:
      - chatainews.co