services:
  - type: web
    name: snappl-pokemon-market
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install .
    startCommand: streamlit run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
    domains:
      - chatainews.co